### ISSUE TITLE
Token counts are different in Mac and Windows versions

### ISSUE THREAD

**Issue by igrodsan** [andreanini/multidimensionalanalysistagger#1] opened 2020-10-15 01:14 UTC
The windows version seems to count more tokens than the Mac version. The count of the Mac version is closer to that of AntConc and Lancsbox.
This situation might be related to whether non-word characters like ' ’ (curly single quote) - (hyphen) etc. are considered part of a word or not.

The following table compares token counts of the same four files with different tools.
Filename | MAT 1.3.2 mac | lancsbox 5.1.2 | AntConc 3.5.8 including ' ’ - _ as token definitions | AntConc 3.5.8 as is | MAT 1.3.2 windows
text1 | 9138 | 8692 | 8693 | 9338 | 11887
text2 | 5497 | 5238 | 5238 | 5601 | 6887
text3 | 4733 | 4499 | 4486 | 4766 | 5878
text4 | 5003 | 4828 | 4828 | 5062 | 5948

**Comment by bertvandepoel** [comment] 2022-04-04 16:19
While porting this code to work with Linux, I think I may have found one of the potential sources for this bug. Everywhere in the code the first 2 files of readdir are ignored, presuming they will be "." and "..". However, on Linux the readdir list does not return in a stable order, so this quickfix doesn't work. Since Mac, as a Unix-like system, is very similar to Mac. I wouldn't be surprised if the Mac version was accidentally sometimes ignoring random files, compared to Windows.

**Comment by andreanini** [comment] 2022-04-05 14:15
Thank you for spotting this problem, Bert. It can be fixed quite easily of course but I will only be able to do this over the summer. I'll add this to some other small changes I wanted to make.

**Comment by bertvandepoel** [comment] 2022-04-05 15:39
If you'd like, I can submit a pull request with the necessary fix. I've had to fix it locally myself in all the files, so it's trivial for me to isolate that patch and send it over as a pull request, but I'm not sure if that fits your way of working with the development of MAT.

**Comment by andreanini** [comment] 2022-04-06 11:49
That would be great! Please do send it.

**Comment by bertvandepoel** [comment] 2022-04-07 08:42
I was thinking. Since I'm already adding a filter for . and .., shouldn't that also include other hidden files and folders like dotfolders, .DS_Store, and thumbs.db?

**Comment by andreanini** [comment] 2022-04-07 15:02
I think perhaps the best strategy is to remove the loop that gives an error if a folder does not contain \.txt files. What do you think? If a folder contains non-.txt files then MAT will only consider the txt files anyway.

**Comment by andreanini** [comment] 2022-09-15 14:07
I have now released a minor update that might have fixed this. @bertvandepoel, I don't think what you identified is an issue. I'm actually quite sure that in macOS the program works as intended. @igrodsan, can you try to repeat the counts with the new version? The version on Mac is the same so you don't have to re-install anything.

**Comment by igrodsan** [comment] 2022-09-15 14:55
Yes, I'll check that in the next few days

**Comment by igrodsan** [comment] 2022-09-22 15:27
Dear Andrea and Bert,
The problem has been resolved 99.9%. I still do not know the reason behind the very small difference in the word count, but it looks to me nearly negligible.
This is the comparison of the token counts of 20 texts in the new windows version and mac:

Filename | Tokens Win | Tokens Mac | dif win-mac
text 1 | 9138 | 9137 | 1
text 2 | 5497 | 5496 | 1
text 3 | 5003 | 4992 | 11
text 4 | 4675 | 4671 | 4
text 5 | 4121 | 4120 | 1
text 6 | 5676 | 5672 | 4
text 7 | 2310 | 2307 | 3
text 8 | 5383 | 5370 | 13
text 9 | 1586 | 1585 | 1
text 10 | 2995 | 2994 | 1
text 11 | 5025 | 5025 | 0
text 12 | 2853 | 2853 | 0
text 13 | 2507 | 2507 | 0
text 14 | 644 | 644 | 0
text 15 | 2954 | 2953 | 1
text 16 | 2404 | 2404 | 0
text 17 | 4750 | 4750 | 0
text 18 | 5285 | 5284 | 1
text 19 | 4799 | 4798 | 1
text 20 | 2235 | 2235 | 0

**Comment by andreanini** [comment] 2022-09-26 10:05
Great. There are always small differences across tokenizers (e.g. compare Antconc vs. Lancsbox) so I'm not concerned about this. I'll close this issue for now but if you happen to notice another problem (e.g. what's happening with text 8?) then please open another one!

**Closed as completed by andreanini** 2022-09-26 10:05 UTC
Labels: bug

**Comment by igrodsan** [comment] 2022-09-26 15:04
Well done! Congrats to you all!
Thanks to your work with this tool several generations of linguists in
Mexico know (and are not scared of) MDA.
Best,

Ignacio


Ignacio Rodríguez Sánchez
Facultad de Lenguas y Letras
Universidad Autónoma de Querétaro
Campus Aeropuerto
Anillo Vial Fray Junípero Serra s/n
C.P. 76140
Querétaro, Qro.
México
tel. + (52) 442 1921200 ext. 61270
https://ignaciorodriguez.weebly.com/
